language: c
install:
  - ./configure
script:
  - make --environment-overrides
compiler:
  - gcc
cache:
  directories:
    - binary
notifications:
  email:
    recipients:
      - dibyendu.das.in@gmail.com
    on_success: never
    on_failure: change